export const product = {
  category: [
    {
      category: 'T-Shirt',
      data: [
        {
          name: 't-shirt 1',
          price: 300,
          quantity: 1,
          gender: 'male',
          image: require('./images/tshirt1.jpg'),
          selected: false,
        },
        {
          name: 't-shirt 2',
          price: 349,
          gender: 'male',
          image: require('./images/tshirt2.jpeg'),
          selected: false,
          quantity: 1,
        },
        {
          name: 't-shirt 3',
          price: 200,
          gender: 'male',
          image: require('./images/tshirt3.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 't-shirt 4',
          price: 299,
          gender: 'male',
          image: require('./images/tshirt4.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 't-shirt 5',
          price: 399,
          gender: 'male',
          image: require('./images/tshirt5.webp'),
          selected: false,
          quantity: 1,
        },
      ],
    },
    {
      category: 'Jeans',
      data: [
        {
          name: 'Jeans 1',
          price: 500,
          gender: 'male',
          image: require('./images/jeans1.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Jeans 2',
          price: 499,
          gender: 'male',
          image: require('./images/jeans2.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Jeans 3',
          price: 599,
          gender: 'male',
          image: require('./images/jeans3.jpeg'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Jeans 4',
          price: 699,
          gender: 'male',
          image: require('./images/jeans4.webp'),
          selected: false,
          quantity: 1,
        },
      ],
    },
    {
      category: 'Shoe',
      data: [
        {
          name: 'Shoes 1',
          price: 1100,
          gender: 'male',
          image: require('./images/shoes1.jpeg'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Shoes 2',
          price: 680,
          gender: 'male',
          selected: false,
          image: require('./images/shoes2.jpeg'),
          quantity: 1,
        },
        {
          name: 'Shoes 3',
          price: 599,
          gender: 'male',
          image: require('./images/shoes3.jpeg'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Shoes 4',
          price: 800,
          gender: 'male',
          image: require('./images/shoes4.jpeg'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Shoes 5',
          price: 1000,
          gender: 'male',
          image: require('./images/shoes5.webp'),
          selected: false,
          quantity: 1,
        },
      ],
    },
    {
      category: 'Jacket',
      data: [
        {
          name: 'Jacket 1',
          price: 1300,
          gender: 'male',
          image: require('./images/jacket1.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Jacket 2',
          price: 999,
          gender: 'male',
          image: require('./images/jacket2.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Jacket 3',
          price: 650,
          gender: 'male',
          image: require('./images/jacket3.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Jacket 4',
          price: 800,
          gender: 'male',
          image: require('./images/jacket4.webp'),
          selected: false,
          quantity: 1,
        },
      ],
    },
    {
      category: 'Slipper',
      data: [
        {
          name: 'Slippers 1',
          price: 250,
          gender: 'male',
          image: require('./images/slipper1.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Slipper 2',
          price: 450,
          gender: 'male',
          image: require('./images/slipper2.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Slipper 3',
          price: 400,
          gender: 'male',
          image: require('./images/slipper3.jpeg'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Slipper 4',
          price: 240,
          gender: 'male',
          image: require('./images/slipper4.jpeg'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Slipper 5',
          price: 399,
          gender: 'male',
          image: require('./images/slipper5.jpeg'),
          selected: false,
          quantity: 1,
        },
      ],
    },
    {
      category: 'Trousers',
      data: [
        {
          name: 'Trousers 1',
          price: 250,
          gender: 'male',
          image: require('./images/trouser1.jpg'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Trousers 2',
          price: 450,
          gender: 'male',
          image: require('./images/trouser2.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Trousers 3',
          price: 400,
          gender: 'male',
          image: require('./images/trouser3.webp'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Trousers 4',
          price: 240,
          gender: 'male',
          image: require('./images/trouser4.jpeg'),
          selected: false,
          quantity: 1,
        },
        {
          name: 'Trousers 5',
          price: 399,
          gender: 'male',
          image: require('./images/trouser5.jpeg'),
          selected: false,
          quantity: 1,
        },
      ],
    },
  ],
};